# Multi-stage build
FROM node:20-alpine AS build
ARG REACT_APP_API_URL
ARG REACT_APP_YOUTUBE_API_KEY
ARG REACT_APP_YOUTUBE_CHANNEL_ID
ARG REACT_APP_ADMIN_EMAIL
ARG REACT_APP_ADMIN_PASSWORD
ARG REACT_APP_ADMIN_NAME
ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_YOUTUBE_API_KEY=$REACT_APP_YOUTUBE_API_KEY
ENV REACT_APP_YOUTUBE_CHANNEL_ID=$REACT_APP_YOUTUBE_CHANNEL_ID
ENV REACT_APP_ADMIN_EMAIL=$REACT_APP_ADMIN_EMAIL
ENV REACT_APP_ADMIN_PASSWORD=$REACT_APP_ADMIN_PASSWORD
ENV REACT_APP_ADMIN_NAME=$REACT_APP_ADMIN_NAME
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.25-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
